services:
  loki:
    image: grafana/loki:3.2.1
    container_name: demoblaze-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro

  promtail:
    image: grafana/promtail:3.2.1
    container_name: demoblaze-promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./logs:/var/log/playwright:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.3.1
    container_name: demoblaze-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: light
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki